{{- $depName := printf "%s" (include "deploymentName" (dict "root" .Values "defaultname" "constellation-messaging" )) }}
{{- $srvPort := .Values.service.port }}{{ if .Values.pegaMessagingPort }}{{ $srvPort = .Values.pegaMessagingPort }}{{ end }}
{{- if .Values.enabled }}
{{- if and (.Values.ingress) (eq .Values.ingress.enabled true) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $depName }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: {{ .Values.urlPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ $depName }}
            port:
              number: {{ $srvPort }}
{{ if (.Values.ingress.tls) }}
{{- if (eq .Values.ingress.tls.enabled true) }}
{{- if .Values.ingress.tls.secretName }}
{{- include "tlssecretsnippet" (dict "node" .Values) | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{ end }}
{{ end }}