{{ $depName := printf "%s" (include "deploymentName" (dict "root" .Values "defaultname" "constellation-messaging" )) }}
{{- $srvTargetPort := .Values.service.targetPort }}{{ if .Values.pegaMessagingTargetPort }}{{ $srvTargetPort = .Values.pegaMessagingTargetPort }}{{ end }}
{{- $srvPort := .Values.service.port }}{{ if .Values.pegaMessagingPort }}{{ $srvPort = .Values.pegaMessagingPort }}{{ end }}
{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $depName }}
  labels:
    app: {{ $depName }}
{{- if and (.Values.service) (.Values.service.annotations) }}
  annotations: 
    # Custom annotations
{{ toYaml .Values.service.annotation | indent 4 }}
{{- else if (eq .Values.provider "gke") }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"https":"HTTPS","http":"HTTP"}'
    cloud.google.com/backend-config: '{"ports": {"{{ $srvPort }}": "{{ $depName }}"}}'
{{- end }}
spec:
  selector:
    app: {{ $depName }}
  ports:
  - name: http
    protocol: TCP
    port: {{ $srvPort }}
    targetPort: {{ $srvTargetPort }}
  type: {{ .Values.service.serviceType }}
{{ end }}
