{{- if and (not .Values.srsStorage.authSecret) (or (eq (include "elasticsearch.authProvider" .) "basic-authentication") (eq (include "elasticsearch.authProvider" .) "tls") (eq (include "elasticsearch.authProvider" .) "mtls"))}}
apiVersion: v1
kind: Secret
metadata:
  name: srs-elastic-credentials
type: kubernetes.io/basic-auth
data:
  username: {{ template "esDeploymentUsername" . }}
  password: {{ template "esDeploymentPassword" . }}
{{end}}