{{- with include "pegaServiceAccountResource" (dict "config" .Values.global.serviceAccount "configPath" "global.serviceAccount" "generatedName" (include "pegaServiceAccountName" .) "namespace" .Release.Namespace) }}
---
{{ . }}
{{- end }}
