{{- if .Values.global.downloadContainer }}
{{- if .Values.global.downloadContainer.image }}
---
# This template contains the script to download the JDBC driver from the specified location and copy it to the shared
# volume. This script will be executed by the init container before starting the Pega application container.
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "pegaLibDownloadScriptConfig" $ }}
  namespace: {{ .Release.Namespace }}
data:
  download-jdbc.sh: |
    #!/bin/sh
    pega_root="/opt/pega"
    lib_root="/opt/pega/lib"
    secret_root="/opt/pega/secret"
    declare -a secrets_list=("CUSTOM_ARTIFACTORY_USERNAME" "CUSTOM_ARTIFACTORY_PASSWORD" "CUSTOM_ARTIFACTORY_APIKEY_HEADER" "CUSTOM_ARTIFACTORY_APIKEY" )
    for secret in "${secret_root}"/*
    do
      basename=$(basename "$secret")
      temp_file="${secret_root}/${basename}"
      export SECRET_"${basename}"="$(<"${temp_file}")"
    done
    for secret in "${secrets_list[@]}"
    do
       temp="SECRET_${secret}"
       secret_value=${!temp}
       if [ "${secret_value}" == ""  ]; then
         export SECRET_"${secret}"="${!secret}"
       fi
    done
    custom_artifactory_auth=""
    if [ "$SECRET_CUSTOM_ARTIFACTORY_USERNAME" != "" ] || [ "$SECRET_CUSTOM_ARTIFACTORY_PASSWORD" != "" ]; then
        if [ "$SECRET_CUSTOM_ARTIFACTORY_USERNAME" == "" ] || [ "$SECRET_CUSTOM_ARTIFACTORY_PASSWORD" == "" ]; then
            echo "SECRET_CUSTOM_ARTIFACTORY_USERNAME & SECRET_CUSTOM_ARTIFACTORY_PASSWORD must be specified for basic authentication for custom artifactory."
            exit 1
        else
            echo "Using basic authentication for custom artifactory to download JDBC driver."
            custom_artifactory_auth="-u "$SECRET_CUSTOM_ARTIFACTORY_USERNAME":"$SECRET_CUSTOM_ARTIFACTORY_PASSWORD
        fi
    fi
    if [[ "$custom_artifactory_auth" == "" && ( "$SECRET_CUSTOM_ARTIFACTORY_APIKEY_HEADER" != "" || "$SECRET_CUSTOM_ARTIFACTORY_APIKEY" != "" ) ]]; then
        if [ "$SECRET_CUSTOM_ARTIFACTORY_APIKEY_HEADER" == "" ] || [ "$SECRET_CUSTOM_ARTIFACTORY_APIKEY" == "" ]; then
            echo "SECRET_CUSTOM_ARTIFACTORY_APIKEY_HEADER & SECRET_CUSTOM_ARTIFACTORY_APIKEY must be specified for authentication using api key for custom artifactory."
            exit 1
        else
            echo "Using API key for authentication of custom artifactory to download JDBC driver."
            custom_artifactory_auth="-H "$SECRET_CUSTOM_ARTIFACTORY_APIKEY_HEADER":"$SECRET_CUSTOM_ARTIFACTORY_APIKEY
        fi
    fi
    custom_artifactory_certificate=''
    if [ "$(ls -A "${pega_root}/artifactory/cert"/*)" ]; then
         if [ "$(ls "${pega_root}/artifactory/cert"/* | wc -l)" == 1 ]; then
           echo "Certificate is provided for custom artifactory's domain ssl verification."
           # get certificate name
           for certfile in "${pega_root}/artifactory/cert"/*
            do
               echo "folder name: ${pega_root}/artifactory/cert"
               filename=$(basename "$certfile")
               ext="${filename##*.}"
               echo "$filename"
               if [[ "$ext" =~ ^(cer|pem|crt|der|cert|jks|p7b|p7c|key)$ ]]; then
                  echo "$certfile"
                  custom_artifactory_certificate="--cacert "$certfile
               else
                  echo "curl needs valid format certificate file for ssl verification."
                  exit 1
               fi
            done
         else
           echo "Provide one certificate file. The file may contain multiple CA certificates."
           exit 1
         fi
    fi
    if [ "$JDBC_DRIVER_URI" != "" ]; then
      curl_cmd_options=''
      if [ "$ENABLE_CUSTOM_ARTIFACTORY_SSL_VERIFICATION" == true ]; then
        echo "Establishing a secure connection to download driver."
        curl_cmd_options="-sSL $custom_artifactory_auth $custom_artifactory_certificate"
      else
        echo "Establishing an insecure connection to download driver."
        curl_cmd_options="-ksSL $custom_artifactory_auth"
      fi
      urls=$(echo "$JDBC_DRIVER_URI" | tr "," "\n")
      for url in $urls
        do
         echo "Downloading database driver: ${url}";
         jarabsurl="$(cut -d'?' -f1 <<<"$url")"
         echo "$jarabsurl"
         filename=$(basename "$jarabsurl")
         if curl $curl_cmd_options --output /dev/null --silent --fail -r 0-0 "$url"
         then
           curl $curl_cmd_options -o ${lib_root}/$filename "${url}"
         else
           echo "Could not download jar from ${url}"
           exit 1
         fi
        done
    fi

{{- end }}
{{- end }}