{{- if and ((.Values.autopilot.autopilotAuth).enabled) (not .Values.autopilot.autopilotAuth.external_secret_name) }}
# Secret that stores the OAuth private key used by Pega Platform to obtain tokens for the Autopilot Service
apiVersion: v1
kind: Secret
metadata:
  name: pega-autopilot-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  privateKey: {{ template "autopilotAuthPrivateKey" . }}
{{- end }}
