{{ if (eq (include "deployNonExtDDSSecret" .) "true") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pega-dds-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  # Base64 encoded username for connecting to cassandra
  {{ if .Values.dds.username -}}
  CASSANDRA_USERNAME: {{ .Values.dds.username | b64enc }}
  {{- end }}

  # Base64 encoded password for connecting to cassandra
  {{ if .Values.dds.password -}}
  CASSANDRA_PASSWORD: {{ .Values.dds.password | b64enc }}
  {{- end }}

  {{ if .Values.dds.trustStorePassword -}}
  # Base64 encoded password for the cassandra trust store
  CASSANDRA_TRUSTSTORE_PASSWORD: {{ .Values.dds.trustStorePassword | b64enc }}
  {{- end }}

  {{ if .Values.dds.keyStorePassword -}}
  # Base64 encoded password for the cassandra key store
  CASSANDRA_KEYSTORE_PASSWORD: {{ .Values.dds.keyStorePassword | b64enc }}
  {{- end }}
{{ end }}