{{- if and ((.Values.autopilot.autopilotAuth).enabled) (not .Values.autopilot.autopilotAuth.external_secret_name) }}
# Secret for OAuth private key used to get an authorization token for Pega Infinity connection to the Autopilot service
apiVersion: v1
kind: Secret
metadata:
  name: pega-autopilot-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  privateKey: {{ template "autopilotAuthPrivateKey" . }}
{{- end }}
