{{- if and (or (eq (include "performInstall" .) "true") (eq (include "performUpgrade" .) "true")) (not .Values.serviceAccountName) }}
{{- with include "pegaServiceAccountResource" (dict "config" .Values.serviceAccount "configPath" "installer.serviceAccount" "generatedName" (include "pegaInstallerServiceAccountDefaultName" .) "namespace" .Release.Namespace) }}
---
{{ . }}
{{- end }}
{{- end }}
