---
{{- if ((eq (include "deployNonExtPegaRESTSecret" .) "true")) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pega-upgrade-rest-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  # Base64 encoded username/password for Pega User REST credentials used for managing
  # ZDT upgrade flags
  {{- if .Values.upgrade }}
  {{- if .Values.upgrade.pegaRESTUsername }}
  PEGA_REST_USERNAME: {{ .Values.upgrade.pegaRESTUsername | b64enc }}
  {{- end }}
  {{- if .Values.upgrade.pegaRESTPassword }}
  PEGA_REST_PASSWORD: {{ .Values.upgrade.pegaRESTPassword | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}