{{ if (eq (include "createJobsReaderRole" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: check-installer-status
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "installerJobReaderRole" }}
subjects:
- kind: ServiceAccount
{{- $config := .Values.serviceAccount }}
{{- if and (not $config.enabled) .Values.global.serviceAccount.enabled }}
{{- $config = .Values.global.serviceAccount }}
{{- end }}
  name: {{ if .Values.serviceAccountName }}{{ .Values.serviceAccountName }}{{ else if $config.name }}{{ $config.name }}{{ else }}{{ include "pegaInstallerServiceAccountName" (dict "root" . "config" $config) }}{{ end }}
  namespace: {{ .Release.Namespace }}
{{ end }}