---
enabled: false
name: YOUR_MESSAGING_SERVICE_DEPLOYMENT_NAME

image: YOUR_MESSAGING_SERVICE_IMAGE:TAG
replicas: 1

# To avoid exposing Docker credentials, create a separate Docker config secret.
# Specify secret names as an array of comma-separated strings. For example: ["secret1", "secret2"]
imagePullSecretNames: []
imagePullPolicy: Always

pegaMessagingPort: 3000
pegaMessagingTargetPort: 3000

# set memoryRequest &  memoryLimit to Limit memory usage for container https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
memoryRequest: # ex: 128Mi for MB or 2Gi for GB
memoryLimit: # ex: 256Mi for GB or 4Gi for GB
# set seccompProfile to RuntimeDefault to not disable default seccomp profile https://kubernetes.io/docs/tutorials/security/seccomp/
seccompProfile: Unconfined  # RuntimeDefault
# DO NOT CHANGE readOnlyRootFilesystem VALUE to true, C11N MESSAGING SERVICE WON'T WORK AS EXPECTED
readOnlyRootFilesystem: false
# set allowPrivilegeEscalation to false to Restrict container from acquiring additional privileges https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
allowPrivilegeEscalation: true # false
serviceType: NodePort

# An ingress will be provisioned if a hostname is defined, or omitted if the hostname is empty.
# ingressClassName and annotations are optional and will be included if defined.
# Due to the diverse requirements for ingresses and TLS configuration, it may be necessary to define the ingress separately from this chart.
ingress:
  domain:
  ingressClassName:
  annotations:
