{{ if and (eq (include "performDeployment" .) "true") (eq (include "isHazelcastEnabled" .) "true") }}
  {{- if (semverCompare ">= 1.21.0-0" (trimPrefix "v" .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: policy/v1
  {{- else }}
apiVersion: policy/v1beta1
  {{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "hazelcastName" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "hazelcastName" . }}
    component: Hazelcast
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "hazelcastName" . }}
      component: Hazelcast
{{- end }}