---
# Traefik load balancer parameters
# Pega deployments support the use of Traefik as the default load balancer; however, by default,
# Pega Platform deployments assume clients will use the load balancing tools featured in the
# Kubernetes environment of the deployment. For more information, see the readme:
# https://github.com/pegasystems/pega-helm-charts/blob/master/charts/addons/README.md
# Set traefik.enabled: true to deploy Traefik using the parameters specified below.
traefik:
  enabled: false
  # When you set this to true, you can then set additional Traefik parameters to be passed into Traefik's Helm chart.
  # See https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  # To use Traefik as a load balancer in PKS, AKS, GKE, or k8s, set traefik.serviceType: "LoadBalancer".
  # Pega does not maintain example values or update addon chart values - refer to the Traefik helm charts
  # for the latest parameters and values.

# When deploying on AWS EKS, set this to true to install aws-load-balancer-controller.
## For more details on this, please refer https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
aws-load-balancer-controller:
  enabled: false
  # Pega does not maintain example values or update addon chart values - refer to the aws-load-balancer-controller
  # helm charts for the latest parameters and values.

# Configure EFK stack for logging:
# For a complete EFK stack: elasticsearch, fluentd-elasticsearch, and kibana should all be enabled
# Pega recommends deploying EFK only on k8s
# On Openshift, see https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html
# On EKS, see https://eksworkshop.com/logging/

# Replace false with true to deploy EFK.
# Do not remove &deploy_efk; it is a yaml anchor which is referenced by the EFK subcharts.
deploy_efk: &deploy_efk false

elasticsearch:
  enabled: *deploy_efk
  # Set any additional elastic search parameters. These values will be used by elasticsearch helm chart.
  # See https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml
  # Pega does not maintain example values or update addon chart values - refer to the elasticsearch
  # helm charts for the latest parameters and values.

kibana:
  enabled: *deploy_efk
  # Set any additional kibana parameters. These values will be used by Kibana's helm chart.
  # See https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml
  # Pega does not maintain example values or update addon chart values - refer to the kibana
  # helm charts for the latest parameters and values.

fluentd-elasticsearch:
  enabled: *deploy_efk
  # Set any additional fluentd-elasticsearch parameters. These values will be used by fluentd-elasticsearch's helm chart.
  # See https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml
  # Pega does not maintain example values or update addon chart values - refer to the fluentd-elasticsearch
  # helm charts for the latest parameters and values.

# Configure a metrics-server tool for the deployment by following the guidelines specific to each provider:
# EKS, open-source Kubernetes, Openshift - set this to true.
# GKE or AKS - set this to false and use the native metrics-server in the cluster.
metrics-server:
  enabled: false
  # Set any additional metrics-server parameters. These values will be used by metrics-server's helm chart.
  # See https://github.com/helm/charts/blob/master/stable/metrics-server/values.yaml
  # Pega does not maintain example values or update addon chart values - refer to the metrics-server
  # helm charts for the latest parameters and values.

# When deploying on Azure AKS, set ingress-azure.enabled to true to install an Application Gateway Ingress Controller (AGIC).
# The AGIC is a pod within your AKS cluster that monitors the Kubernetes Ingress resources, and creates and applies the
# Application Gateway config based on the status of the Kubernetes cluster. For details, see
# (https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-existing#azure-resource-manager-authentication).
ingress-azure:
  enabled: false
  # Pega does not maintain example values or update addon chart values - refer to the ingress-azure
  # helm charts for the latest parameters and values.
